name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS Credentials For GitHub Actions
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: "eu-west-2"

    - name: Terraform Init
      run: terraform -chdir='./terraform' init

    - name: Terraform Format
      run: terraform -chdir='./terraform' fmt -check

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: terraform -chdir='./terraform' apply -auto-approve -input=false
